//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oceanbnb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OceanbnbDbEntities : DbContext
    {
        public OceanbnbDbEntities()
            : base("name=OceanbnbDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cruis> Cruises { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationsToCruis> LocationsToCruises { get; set; }
        public virtual DbSet<Ship> Ships { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersToCruis> UsersToCruises { get; set; }
    }
}
