//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oceanbnb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersToCruis
    {
        public int UsersToCruisesId { get; set; }
        public int UserId { get; set; }
        public int CruiseId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateInserted { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual Cruis Cruis { get; set; }
        public virtual User User { get; set; }
    }
}
