//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ship()
        {
            this.Cruises = new HashSet<Cruis>();
        }
    
        public int ShipId { get; set; }
        public string ShipName { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public Nullable<int> PassengerCapacity { get; set; }
        public Nullable<int> CrewCount { get; set; }
        public Nullable<int> WeightInTons { get; set; }
        public Nullable<int> LengthInMeters { get; set; }
        public Nullable<int> BeamInMeters { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cruis> Cruises { get; set; }
    }
}
